#!/bin/sh
#
# make install
# adds hyperv labels in loader.conf 
#

if [ "$1" = "PRE-INSTALL" ]; then
echo "===> Pre-install Check"
# KVP - Directories Check

echo "===> Checking KVP directories" 
kvp_dir="/var/db/hyperv/"
kvp_dir_scripts="/var/db/hyperv/scripts"

if [ -d $kvp_dir ]; then
   if [ -d $kvp_dir_scripts ]; then
      echo " ### KVP Directories present " 
   else 
      echo " ### Creating $kvp_dir_scripts directory "
      mkdir /var/db/hyperv/scripts
   fi
else 
   echo " xxx KVP directories not found"
   echo " ### Creating KVP  directories "
   mkdir /var/db/hyperv
   mkdir /var/db/hyperv/scripts
fi

else if [ "$1" = "POST-INSTALL" ]; then
   test="/boot/loader.conf"

fi
fi
exit 0
